apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${IMAGE_NAME}
  namespace: core
  labels:
    app: ${IMAGE_NAME}
    squad: core
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: ${IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${IMAGE_NAME}
        squad: core
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        warpin: services 
      containers:
        - image: asia.gcr.io/warung-support/${IMAGE_NAME}:${IMAGE_VERSION}
          name: ${IMAGE_NAME}
          imagePullPolicy: Always
          env:
            - name: RELEASE_DATE
              value: "${CI_PIPELINE_ID}"
            - name: ENV_STAG
              value: "${ENV_STAGE}"
          ports:
            - containerPort: 9000
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 20
      imagePullSecrets:
        - name: gcr-json-key
---
apiVersion: v1
kind: Service
metadata:
  name: ${IMAGE_NAME}
  namespace: core
  labels:
    app: ${IMAGE_NAME}
spec:
  type: NodePort
  ports:
    - name: http-${IMAGE_NAME}
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: ${IMAGE_NAME}
